// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_N3-2B7-_rLQATQ2u0MPJ4K1IflNgjk',
    appId: '1:449277276440:android:0526c86852ffb6c4a02e6d',
    messagingSenderId: '449277276440',
    projectId: 'veloxi-7aaf6',
    databaseURL: 'https://veloxi-7aaf6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'veloxi-7aaf6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByCzhiPZZvVFYFA0ZkIqVSh6uLgCSE6SQ',
    appId: '1:449277276440:ios:ab70f978b649e6d9a02e6d',
    messagingSenderId: '449277276440',
    projectId: 'veloxi-7aaf6',
    databaseURL: 'https://veloxi-7aaf6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'veloxi-7aaf6.firebasestorage.app',
    androidClientId: '449277276440-j2lfvo4d253rlqj4hm28j3qpajgbjjgs.apps.googleusercontent.com',
    iosClientId: '449277276440-t7qm7l51c592ob3loc1c92ghep24ij11.apps.googleusercontent.com',
    iosBundleId: 'com.tsdigital.veloxiapp',
  );
}
